import type { Reference } from './types'

export const DEMO_REFERENCES: Reference[] = [
  {
    id: '1',
    title: 'Premium Fashion-Messestand',
    branche: 'kleidung',
    size: '80 qm',
    type: 'messebau',
    imageUrl: '/images/deligreece-messestand-100qm-food.jpeg',
    description: 'Eleganter Messestand mit stilvoller Kollektionspräsentation und VIP-Lounge für Einkäufer',
    challenge: 'Ein Mode-Unternehmen benötigte einen Stand, der die aktuelle Kollektion hochwertig inszeniert und zugleich exklusive Beratungsgespräche mit Einkäufern ermöglicht.',
    solution: 'Wir entwickelten ein offenes Konzept mit beleuchteten Garderobenbereichen, großformatigen Lifestyle-Bildern und einer einladenden VIP-Lounge für B2B-Gespräche.',
    result: 'Deutlich mehr Besucherkontakte, zahlreiche neue Handelspartner-Leads',
    keyfacts: ['80 qm Standfläche', '3 Tage Aufbau', 'Nachhaltige Systemelemente'],
    messe: 'Gallery Shoes Düsseldorf',
    zielsetzung: 'Hochwertige Kollektionspräsentation und B2B-Kontaktgenerierung für die kommende Saison'
  },
  {
    id: '2',
    title: 'Design-Stand mit Markenpräsentation',
    branche: 'sport',
    size: '12 qm',
    type: 'messebau',
    imageUrl: '/images/fda8df74-ab46-44c7-a6ca-ebfc6c9b4850.jpeg',
    description: 'Moderner Messestand mit offenen Präsentationsbereichen und eleganter Markendarstellung',
    challenge: 'Ein Fashion-/Design-Unternehmen benötigte einen Stand, der Produkte ästhetisch in Szene setzt und gleichzeitig Raum für Kundengespräche bietet.',
    solution: 'Klare Raumzonierung: Offene Welcome-Area, Produktpräsentationszonen und digitale Infoscreens für interaktive Markenerlebnisse.',
    result: 'Über 300 Besucherkontakte, sehr positive Feedbacks zur Standgestaltung und Produktpräsentation',
    keyfacts: ['12 qm Standfläche', 'Modulares System', '2 Beratungsplätze'],
    messe: 'DKM Dortmund',
    zielsetzung: 'Ästhetische Markenpräsenz mit effizienten Kommunikationszonen für Kundengespräche'
  },
  {
    id: '3',
    title: 'Showroom für Produktpräsentation',
    branche: 'ladenbau',
    size: '120 qm',
    type: 'ladenbau',
    imageUrl: '/images/ladenbau/showroom-bodenproben-ausstellung.jpg',
    description: 'Permanenter Showroom mit hochwertiger Produktpräsentation',
    challenge: 'Produkte ansprechend präsentieren und Markenkompetenz vermitteln in einem dauerhaften Ausstellungsraum.',
    solution: 'Moderner Look mit hochwertigen Details: Sichtbeton-Optik, LED-Spots, interaktive Produktkonfiguratoren.',
    result: 'Dauerhafter Showroom mit regelmäßigen Kundenführungen und positivem Markenimage',
    keyfacts: ['120 qm Showroom', 'Permanent-Installation', 'Integrierte Medienwände', 'Barrierefreier Zugang'],
    messe: 'Hannover Messe',
    zielsetzung: 'Permanenter Showroom zur Demonstration von Kompetenz und Produktvielfalt'
  },
  {
    id: '4',
    title: 'Nachhaltiger Messestand mit Bio-Konzept',
    branche: 'messebau',
    size: '25 qm',
    type: 'messebau',
    imageUrl: '/images/03e69940-1b4a-4555-9c29-e3bb8c2564b3.jpeg',
    description: 'Nachhaltiger Messestand für Bio-Feinkost mit Verkostungsbereich und B2B-Kontaktzone',
    challenge: 'Ein Bio-Food-Startup musste Premium-Produkte überzeugend präsentieren und gezielt B2B-Kontakte generieren.',
    solution: 'Warme Materialien, einladende Verkostungsstationen, LED-Produktpräsentation und gezielte Gesprächszonen für Einkäufer.',
    result: 'Zahlreiche B2B-Kontakte und Listungsvereinbarungen mit Feinkost-Händlern',
    keyfacts: ['25 qm', 'Verkostungstheken', 'Nachhaltige Materialien'],
    messe: 'ISM Köln',
    zielsetzung: 'Premium-Produktpräsentation und B2B-Kontaktgenerierung für Markteintritt'
  },
  {
    id: '5',
    title: 'Food-Messestand mit Verkostungsbereich',
    branche: 'messebau',
    size: '90 qm',
    type: 'messebau',
    imageUrl: '/images/deligreece-messestand-100qm-food-2.jpeg',
    description: 'Temperaturkontrollierter Messestand für handgefertigte Confiserie-Produkte',
    challenge: 'Ein Chocolatier benötigte temperaturkontrollierte Produktpräsentation auf der ISM.',
    solution: 'Integrierte Kühlung, kunstvolle Displayvitrinen und beleuchtete Markenwand für maximale Produktinszenierung.',
    result: 'Deutlich mehr Besucherkontakte im Vergleich zum Vorjahr',
    keyfacts: ['90 qm', 'Kühlvitrinen', 'Markeninszenierung'],
    messe: 'ISM Köln',
    zielsetzung: 'Optimale Produktpräsentation unter Temperaturkontrolle für Premiumschokolade'
  },
  {
    id: '6',
    title: 'Klassischer Messestand mit Beratungszonen',
    branche: 'messebau',
    size: '35 qm',
    type: 'messebau',
    imageUrl: '/images/1a5f3965-6bc4-478c-95e1-a97df5fec326.jpeg',
    description: 'Professioneller Messestand mit semi-privaten Beratungsräumen und digitalen Präsentationsflächen',
    challenge: 'Ein Unternehmen benötigte einen Stand, der professionelle Beratungsgespräche in offener Messeatmosphäre ermöglicht.',
    solution: 'Semi-private Beratungsräume, warme Beleuchtung und digitale Produktwände für interaktive Präsentationen.',
    result: 'Über 250 qualifizierte Leads und sehr positive Bewertungen zur Standgestaltung',
    keyfacts: ['35 qm', '4 Beratungsplätze', 'Digital Signage'],
    messe: 'DKM Dortmund',
    zielsetzung: 'Professionelle Standgestaltung mit maximaler Beratungskapazität'
  },
  {
    id: '7',
    title: 'Roadshow-Ausstellung mit Firmenchronik',
    branche: 'eventbau',
    size: '200 qm',
    type: 'eventbau',
    imageUrl: '/images/e859a873-049d-4f2b-9156-0ac94939c636.jpeg',
    description: 'Große Roadshow-Ausstellung mit professioneller Traversen-Konstruktion, Corporate-Design und historischer Firmenausstellung',
    challenge: 'Ein Unternehmen plante eine große Roadshow-Veranstaltung zur Präsentation seiner Firmengeschichte mit aufwändiger Zelt-Ausstellung, professioneller Beleuchtung und blauem Corporate Design.',
    solution: 'Wir realisierten eine beeindruckende Zelt-Installation mit Traversen-System, professioneller Beleuchtungstechnik, blauem Teppichboden im Corporate Design und einer chronologischen Ausstellungsfläche mit historischen Exponaten und Dokumentationen.',
    result: 'Erfolgreiche Roadshow mit hoher Besucherresonanz, eindrucksvolle Inszenierung der Unternehmensgeschichte',
    keyfacts: ['200 qm Ausstellungsfläche', 'Traversen-Konstruktion', 'Professionelle Beleuchtung', 'Corporate Design'],
    messe: 'Roadshow-Tour',
    zielsetzung: 'Eindrucksvolle Präsentation der Firmenhistorie in einer großen Zelt-Ausstellung mit professioneller Event-Technik'
  },
  {
    id: '10',
    title: 'Galerie-Ausstellung & Kunstmesse',
    branche: 'eventbau',
    size: '150 qm',
    type: 'eventbau',
    imageUrl: '/images/980a1068-ecee-48de-86a3-8635874252e4.jpeg',
    description: 'Elegante Galerie-Installation mit weißen Theken, Kunstpräsentation und moderner Beleuchtung',
    challenge: 'Eine Kunstmesse benötigte eine hochwertige Ausstellungsinstallation mit eleganten Präsentationsflächen für Kunstwerke, modernem Galerie-Ambiente und professioneller Beleuchtung.',
    solution: 'Wir entwickelten eine cleane Galerie-Atmosphäre mit weißen Theken und Ausstellungsflächen, gezielter Spotbeleuchtung für optimale Kunstpräsentation und einem offenen, einladenden Raumkonzept für Besucher.',
    result: 'Erfolgreiche Kunstausstellung mit professionellem Galerie-Charakter und positiver Resonanz von Künstlern und Besuchern',
    keyfacts: ['150 qm Ausstellungsfläche', 'Weiße Theken-Systeme', 'Gezielte Beleuchtung'],
    messe: 'Kunstmesse',
    zielsetzung: 'Elegante Galerie-Installation für hochwertige Kunstpräsentation mit modernem Ausstellungsdesign',
  },
  {
    id: '8',
    title: 'Messestand mit Display-Rahmen und Branding',
    branche: 'messebau',
    size: '30 qm',
    type: 'messebau',
    imageUrl: '/images/6da797c7-d75b-4d81-bdb4-81b33663b633.jpeg',
    description: 'Kompakter Messestand mit professionellen Display-Rahmen und markengerechter Gestaltung',
    challenge: 'Ein Unternehmen benötigte einen kompakten Messestand mit hoher Markenwirkung und flexiblen Displayflächen für wechselnde Kampagnen.',
    solution: 'Einsatz hochwertiger Display-Rahmen mit Wechselgrafiken, beleuchtete Rückwand und flexible Standelemente für maximale Wirkung auf kleiner Fläche.',
    result: 'Professioneller Markenauftritt mit flexiblen Wechselmöglichkeiten für Grafiken und Inhalte',
    keyfacts: ['30 qm', 'Display-Rahmen-System', 'Wechselgrafiken'],
    messe: 'EuroShop Düsseldorf',
    zielsetzung: 'Maximale Markenwirkung auf kompakter Fläche mit flexiblen Displaylösungen'
  },
  {
    id: '9',
    title: 'Produktpräsentation mit Rahmen-Display-System',
    branche: 'messebau',
    size: '45 qm',
    type: 'messebau',
    imageUrl: '/images/9412bc1d-704a-4bfb-bf51-d0f1b009e2da.jpeg',
    description: 'Messestand mit großformatigen Rahmen-Displays zur effektvollen Produktinszenierung',
    challenge: 'Ein Unternehmen suchte eine eindrucksvolle Lösung zur Produktpräsentation mit großformatigen Grafikflächen und gutem Besucherfluss.',
    solution: 'Wir konzipierten einen Stand mit freistehenden Rahmen-Display-Systemen, die beidseitig bedruckt und hinterleuchtet werden können – kombiniert mit einer offenen Besucherführung.',
    result: 'Hohe Aufmerksamkeit und Besucherfrequenz dank großflächiger, leuchtender Markengrafiken',
    keyfacts: ['45 qm', 'Hinterleuchtete Displays', 'Beidseitige Grafiken'],
    messe: 'FIBO Köln',
    zielsetzung: 'Eindrucksvolle, großflächige Produktinszenierung mit modernen Display-Rahmen-Systemen'
  }
]
