import type { Reference } from './types'

export const DEMO_REFERENCES: Reference[] = [
  {
    id: '1',
    title: 'Premium Fashion-Messestand',
    branche: 'kleidung',
    size: '80 qm',
    type: 'messebau',
    imageUrl: '/images/deligreece-messestand-100qm-food.jpeg',
    description: 'Eleganter Messestand mit stilvoller Kollektionspräsentation und VIP-Lounge für Einkäufer',
    challenge: 'Ein Mode-Unternehmen benötigte einen Stand, der die aktuelle Kollektion hochwertig inszeniert und zugleich exklusive Beratungsgespräche mit Einkäufern ermöglicht.',
    solution: 'Wir entwickelten ein offenes Konzept mit beleuchteten Garderobenbereichen, großformatigen Lifestyle-Bildern und einer einladenden VIP-Lounge für B2B-Gespräche.',
    result: 'Deutlich mehr Besucherkontakte, zahlreiche neue Handelspartner-Leads',
    keyfacts: ['80 qm Standfläche', '3 Tage Aufbau', 'Nachhaltige Systemelemente'],
    zielsetzung: 'Hochwertige Kollektionspräsentation und B2B-Kontaktgenerierung für die kommende Saison'
  },
  {
    id: '2',
    title: 'Design-Stand mit Markenpräsentation',
    branche: 'sport',
    size: '12 qm',
    type: 'messebau',
    imageUrl: '/images/fda8df74-ab46-44c7-a6ca-ebfc6c9b4850.jpeg',
    description: 'Moderner Messestand mit offenen Präsentationsbereichen und eleganter Markendarstellung',
    challenge: 'Ein Fashion-/Design-Unternehmen benötigte einen Stand, der Produkte ästhetisch in Szene setzt und gleichzeitig Raum für Kundengespräche bietet.',
    solution: 'Klare Raumzonierung: Offene Welcome-Area, Produktpräsentationszonen und digitale Infoscreens für interaktive Markenerlebnisse.',
    result: 'Über 300 Besucherkontakte, sehr positive Feedbacks zur Standgestaltung und Produktpräsentation',
    keyfacts: ['12 qm Standfläche', 'Modulares System', '2 Beratungsplätze'],
    zielsetzung: 'Ästhetische Markenpräsenz mit effizienten Kommunikationszonen für Kundengespräche'
  },
  {
    id: '3',
    title: 'Showroom für Produktpräsentation',
    branche: 'ladenbau',
    size: '120 qm',
    type: 'ladenbau',
    imageUrl: '/images/ladenbau/showroom-bodenproben-ausstellung.jpg',
    description: 'Permanenter Showroom mit hochwertiger Produktpräsentation',
    challenge: 'Produkte ansprechend präsentieren und Markenkompetenz vermitteln in einem dauerhaften Ausstellungsraum.',
    solution: 'Moderner Look mit hochwertigen Details: Sichtbeton-Optik, LED-Spots, interaktive Produktkonfiguratoren.',
    result: 'Dauerhafter Showroom mit regelmäßigen Kundenführungen und positivem Markenimage',
    keyfacts: ['120 qm Showroom', 'Permanent-Installation', 'Integrierte Medienwände', 'Barrierefreier Zugang'],
    zielsetzung: 'Permanenter Showroom zur Demonstration von Kompetenz und Produktvielfalt'
  },
  {
    id: '4',
    title: 'Nachhaltiger Messestand mit Bio-Konzept',
    branche: 'messebau',
    size: '25 qm',
    type: 'messebau',
    imageUrl: '/images/03e69940-1b4a-4555-9c29-e3bb8c2564b3.jpeg',
    description: 'Nachhaltiger Messestand für Bio-Feinkost mit Verkostungsbereich und B2B-Kontaktzone',
    challenge: 'Ein Bio-Food-Startup musste Premium-Produkte überzeugend präsentieren und gezielt B2B-Kontakte generieren.',
    solution: 'Warme Materialien, einladende Verkostungsstationen, LED-Produktpräsentation und gezielte Gesprächszonen für Einkäufer.',
    result: 'Zahlreiche B2B-Kontakte und Listungsvereinbarungen mit Feinkost-Händlern',
    keyfacts: ['25 qm', 'Verkostungstheken', 'Nachhaltige Materialien'],
    zielsetzung: 'Premium-Produktpräsentation und B2B-Kontaktgenerierung für Markteintritt'
  },
  {
    id: '5',
    title: 'Food-Messestand mit Verkostungsbereich',
    branche: 'messebau',
    size: '90 qm',
    type: 'messebau',
    imageUrl: '/images/deligreece-messestand-100qm-food-2.jpeg',
    description: 'Temperaturkontrollierter Messestand für handgefertigte Confiserie-Produkte',
    challenge: 'Ein Chocolatier benötigte temperaturkontrollierte Produktpräsentation auf der ISM.',
    solution: 'Integrierte Kühlung, kunstvolle Displayvitrinen und beleuchtete Markenwand für maximale Produktinszenierung.',
    result: 'Deutlich mehr Besucherkontakte im Vergleich zum Vorjahr',
    keyfacts: ['90 qm', 'Kühlvitrinen', 'Markeninszenierung'],
    zielsetzung: 'Optimale Produktpräsentation unter Temperaturkontrolle für Premiumschokolade'
  },
  {
    id: '6',
    title: 'Klassischer Messestand mit Beratungszonen',
    branche: 'messebau',
    size: '35 qm',
    type: 'messebau',
    imageUrl: '/images/1a5f3965-6bc4-478c-95e1-a97df5fec326.jpeg',
    description: 'Professioneller Messestand mit semi-privaten Beratungsräumen und digitalen Präsentationsflächen',
    challenge: 'Ein Unternehmen benötigte einen Stand, der professionelle Beratungsgespräche in offener Messeatmosphäre ermöglicht.',
    solution: 'Semi-private Beratungsräume, warme Beleuchtung und digitale Produktwände für interaktive Präsentationen.',
    result: 'Über 250 qualifizierte Leads und sehr positive Bewertungen zur Standgestaltung',
    keyfacts: ['35 qm', '4 Beratungsplätze', 'Digital Signage'],
    zielsetzung: 'Professionelle Standgestaltung mit maximaler Beratungskapazität'
  },
  {
    id: '7',
    title: 'Galerie-Ausstellung & Marken-Showroom',
    branche: 'eventbau',
    size: '150 qm',
    type: 'eventbau',
    imageUrl: '/images/WhatsApp%20Image%202026-02-15%20at%2018.25.23.jpeg',
    description: 'Hochwertige Galerie-Ausstellung mit modularen Marken-Countern und eleganter Produktpräsentation in architektonischem Ambiente',
    challenge: 'Mehrere Premium-Marken sollten in einer anspruchsvollen Galerieumgebung gleichwertig und hochwertig präsentiert werden – mit klarer Markenidentität pro Counter.',
    solution: 'Modulare, weiße Ausstellungstheken mit integrierten Markenlogos, individuellen Stehleuchten und Produktdisplays. Offene Raumgestaltung mit Sichtbeton-Architektur und Oberlicht für natürliche Beleuchtung.',
    result: 'Eindrucksvolle Markenpräsentation in Galeriequalität, hohe Besucherverweildauer und positive Resonanz aller teilnehmenden Marken',
    keyfacts: ['150 qm Ausstellungsfläche', 'Multi-Marken-Konzept', 'Galerie-Ambiente', 'Integrierte Beleuchtung'],
    messe: 'Kunst- & Design-Ausstellung',
    zielsetzung: 'Premium-Markenpräsentation mehrerer Brands in hochwertigem Galerie-Setting mit architektonischem Anspruch'
  },
  {
    id: '10',
    title: 'Hockey EM Event-Shop',
    branche: 'sport',
    size: '200 qm',
    type: 'eventbau',
    imageUrl: '/images/980a1068-ecee-48de-86a3-8635874252e4.jpeg',
    description: 'Kompletter Shopaufbau für die EuroHockey Championships in Mönchengladbach',
    challenge: 'THW Sport benötigte einen vollständigen Event-Shop für die Hockey EM mit professionellem Verkaufsraum, Umkleidekabinen und EuroHockey-Branding.',
    solution: 'Wir entwickelten einen modularen Shop mit Verkaufsraum für Adidas Hockey- und Padel-Ausrüstung, separaten Umkleidekabinen mit Vorhängen und Spiegeln sowie einem einladenden Empfangsbereich mit EuroHockey Championships Branding.',
    result: 'Erfolgreicher Event-Shop mit hoher Besucherfrequenz während der gesamten Turnierzeit',
    keyfacts: ['200 qm Event-Shop', 'Verkaufsraum + Umkleiden', 'Adidas Hockey Ausrüstung'],
    zielsetzung: 'Professioneller Event-Shop für Hockey EM mit vollständiger Verkaufs- und Serviceinfrastruktur',
  }
]
